[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "zimtum"
version = "0.0.1"
description = "Zero-Inflated scMPRA Testing and Uncertainty Modeling"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    {name = "Reilly Lab, Yale University"},
]

[project.urls]
Repository = "https://github.com/Reilly-Lab-Yale/tabula-rasa"

[tool.setuptools.packages.find]
include = ["scMPRAforge*"]
